# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://docs.rubocop.org/rubocop/configuration
# https://github.com/rubocop/rubocop/blob/master/config/default.yml
AllCops: 
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'config/environments/**/*'

Bundler/OrderedGems:
  Enabled: false

Layout/LineLength:
  Enabled: false

Style/FetchEnvVar:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

convention:Metrics/BlockLength:
  Enabled: false
convention:Style/Documentation:
  Enabled: false
convention:Metrics/ClassLength:
  Enabled: false
convention:Metrics/MethodLength:
  Enabled: false
convention:Metrics/AbcSize:
  Enabled: false
convention:Metrics/PerceivedComplexity:
  Enabled: false
convention:Metrics/CyclomaticComplexity:
  Enabled: false
convention:Style/GuardClause:
  Enabled: false
convention:Style/IfUnlessModifier:
  Enabled: false
