sudo: false
notifications:
  email: false
addons:
  postgresql: "9.4"
services:
  - postgresql
language: ruby
script: "bundle exec rake"
bundler_args: "--without development production"
before_install:
  - gem update --system
  - gem install bundler
before_script:
  - psql --version
  - psql -c 'create database "weg-li_test";' -U postgres
  - RAILS_ENV=test bundle exec rake db:test:prepare
