version: "3.8"

services:
  redis:
    image: "redis"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: weg-li_development
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    build: .
    environment:
      RAILS_ENV: development
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    env_file: .env
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - redis
  
volumes:
  gem_cache:
  db_data:
  node_modules:
