version: "3.0"
services:
  ruby_server:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    depends_on:
      - postgres_server
    ports:
      - 3000:3000
    networks:
       weg-li_net:
         ipv4_address: 172.28.1.1

  postgres_server:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: weg-li_development
    ports:
      - 5432:5432
    networks:
      weg-li_net:
        ipv4_address: 172.28.1.2

networks:
  weg-li_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16