version: "3.0"
services:
  ruby_server:
    image: ruby:2.6.6
    depends_on:
      - postgres_server
    ports:
      - 3000:3000
    command: /weg-li/script/setup_and_serve
    environment:
      DATABASE: postgres_server
    volumes:
      - ../:/weg-li

  postgres_server:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: weg-li_development
    ports:
      - 5432:5432
