---
openapi: 3.0.1
info:
  title: API V1
  version: v1
components:
  securitySchemes:
    ApiKeyAuth:        # arbitrary name for the security scheme
      type: apiKey
      in: header       # can be "header", "query" or "cookie"
      name: X-API-KEY  # name of the header, query parameter or cookie

security:
  - ApiKeyAuth: 'X-API-KEY'

paths:
  "/api/notices/{id}":
    get:
      summary: Retrieves a notice
      tags:
      - Notices
      produces:
      - application/json
      - application/xml
      parameters:
      - name: id
        in: path
        schema:
          type: string
        required: true
      security:
      - ApiKeyAuth: X-API-KEY
      responses:
        '200':
          description: name found
          schema:
            type: object
            properties:
              token:
                type: string
              status:
                type: string
            required:
            - token
            - status
        '404':
          description: notice not found
