---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/notices/{id}":
    get:
      summary: Retrieves a notice
      tags:
      - Notices
      parameters:
      - name: id
        in: path
        schema:
          type: string
        required: true
      security:
      - ApiKeyAuth: X-API-KEY
      responses:
        '200':
          description: notice found
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: 21f96e417ca2050a075d2cb056a4f670
                  status:
                    type: string
                  street:
                    type: string
                  zip:
                    type: string
                  city:
                    type: string
                  latitude:
                    type: number
                  longitude:
                    type: number
                  registration:
                    type: string
                  color:
                    type: string
                  brand:
                    type: string
                  charge:
                    type: string
                  date:
                    type: string
                    format: date-time
                  severity:
                    type: string
                  vehicle_empty:
                    type: boolean
                  hazard_lights:
                    type: boolean
                  expired_tuv:
                    type: boolean
                  expired_eco:
                    type: boolean
                  duration:
                    type: integer
                required:
                - token
                - status
        '404':
          description: notice not found
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY
servers:
- url: "{defaultUrl}"
  variables:
    defaultUrl:
      default: https://www.weg.li
