---
openapi: 3.0.1
info:
  title: API V1
  version: v1
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY
securityDefinitions:
  ApiKeyAuth:
    type: apiKey
    name: X-API-KEY
    in: header
paths:
  "/api/notices/{id}":
    get:
      summary: Retrieves a notice
      tags:
      - Notices
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        schema:
          type: string
        required: true
      security:
      - ApiKeyAuth: X-API-KEY
      responses:
        '200':
          description: notice found
          schema:
            type: object
            properties:
              token:
                type: string
              status:
                type: string
            required:
            - token
            - status
        '404':
          description: notice not found
