---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/notices/{id}":
    get:
      summary: Retrieves a notice
      tags:
      - Notices
      parameters:
      - name: id
        in: path
        schema:
          type: string
        required: true
      security:
      - ApiKeyAuth: X-API-KEY
      responses:
        '200':
          description: notice found
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  status:
                    type: string
                required:
                - token
                - status
        '404':
          description: notice not found
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY
servers:
- url: "{defaultUrl}"
  variables:
    defaultUrl:
      default: https://www.weg.li
