development:
  adapter: postgresql
  database: weg-li_development
  username: postgres
  host: localhost
  encoding: utf8

test:
  adapter: postgresql
  database: weg-li_test
  username: postgres
  host: localhost
  encoding: utf8

production:
  encoding: utf8
  pool: <%= ENV['RAILS_MAX_THREADS'] || 10 %>
