development:
  adapter: postgresql
  database: weg-li_development
  username: postgres
  host: <%= ENV["POSTGRES_HOST"] || "localhost" %>
  encoding: utf8

test:
  adapter: postgresql
  database: weg-li_test
  username: postgres
  host: <%= ENV["POSTGRES_HOST"] || "localhost" %>
  encoding: utf8

production:
  adapter: postgresql
  url: <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV['RAILS_MAX_THREADS'] || 10 %>
  encoding: utf8
