# check via Rufus::Scheduler.parse
analytics:
   cron: '0 6 * * * Europe/Berlin'
   class: 'Scheduled::AnalyticsJob'
stuck:
   cron: '0 * * * * * Europe/Berlin'
   class: 'Scheduled::StuckJob'
restart:
   cron: '0,5,10,15,20,25,30,35,40,45,50,55 * * * * Europe/Berlin'
   class: 'Scheduled::RestartJob'
activation_reminder:
  cron: '10 8 * * mon Europe/Berlin'
  class: 'Scheduled::ActivationReminderJob'
usage_reminder:
  cron: '20 8 * * mon Europe/Berlin'
  class: 'Scheduled::UsageReminderJob'
expiring_reminder:
  cron: '30 8 * * mon Europe/Berlin'
  class: 'Scheduled::ExpiringReminderJob'
geocoding_cleanup:
  cron: '0 7 * * * Europe/Berlin'
  class: 'Scheduled::GeocodingCleanupJob'
export:
  cron: '0 3 * * mon Europe/Berlin'
  class: 'Scheduled::ExportJob'
