# check via Rufus::Scheduler.parse
analytics:
   cron: '0 6 * * * Europe/Berlin'
   class: 'Scheduled::AnalyticsJob'
activation_reminder:
  cron: '10 8 * * mon Europe/Berlin'
  class: 'Scheduled::ActivationReminderJob'
usage_reminder:
  cron: '20 8 * * mon Europe/Berlin'
  class: 'Scheduled::UsageReminderJob'
expiring_reminder:
  cron: '30 8 * * mon Europe/Berlin'
  class: 'Scheduled::ExpiringReminderJob'
geocoding_cleanup:
  cron: '0 7 * * * Europe/Berlin'
  class: 'Scheduled::GeocodingCleanupJob'
export:
  cron: '0 3 * * mon Europe/Berlin'
  class: 'Scheduled::ExportJob'
