test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>
  public: true

google_development:
  service: GCS
  project: "weg-li"
  bucket: "weg-li-development"
  credentials: "<%= Rails.root.join("config/secrets/gcloud.json") %>"
  public: true

google_production:
  service: GCS
  project: "weg-li"
  bucket: "weg-li-production"
  credentials: <%= ENV['GOOGLE_APPLICATION_CREDENTIALS'].as_json %>
  public: true
