name: Rails Tests MacOS

on: [push]

jobs:
  build:
    runs-on: macos-latest


    steps:

      - uses: actions/checkout@v1

      - name: Install Postgres
        run: brew install postgresql

      - name: Start Postgres
        run: pg_ctl -D /usr/local/var/postgres start

      - name: Install yarn dependencies
        run: yarn install --ignore-engines

      - name: Install bundle
        run:  |
          bundle config set without 'development production'
          bundle install

      - name: Install Imagemagick
        run: brew install imagemagick

      - name: Create database and postgres user
        env:
          PGHOST: localhost
          RAILS_ENV: test
        run: |
          createuser postgres --createdb
          psql -c 'create database "weg-li_test";' -U postgres
          bundle exec rake db:test:prepare

      - name: Run Tests
        env:
          PGHOST: localhost
          PGUSER: postgres
          RAILS_ENV: test
        run: bundle exec rake